# Generated by Django 3.2 on 2023-08-24 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodvendor',
            name='user',
            field=models.CharField(default='victor', max_length=200),
        ),
    ]
